dispatchers:
  - polling_interval: 60
    batch_size: 512
    concurrency_maintenance_interval: 322
workers:
  - queues: "*"
    threads: 3
    polling_interval: 60
  - queues: [ real_time, background ]
    threads: 5
    polling_interval: 60
    processes: 3